title: Testimonials
modelClass: Katana\Testimonials\Models\Testimonials
list: $/katana/testimonials/models/testimonials/columns.yaml
recordUrl: 'katana/testimonials/testimonials/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
